# -*- coding: utf-8 -*-

from odoo import api, fields, models, tools


class PayslipResume(models.Model):
    _name = "payslip.resume"
    _description = "Hr Payslip Report"

    payslip_config_id = fields.Many2one('hr.payslip.config', 'Configuration etat de paie', readonly=True)
    payslip_reference = fields.Char(u'Référence bulletin', size=254, readonly=True)
    employee_id = fields.Many2one('hr.employee', string=u'Id employé', readonly=True)
    department_id = fields.Many2one('hr.department', string='Départment', readonly=True)
    department_parent_id = fields.Many2one('hr.department', string='Département parent', readonly=True)
    nom_employe = fields.Char(u'Nom employé', size=254, readonly=True)
    poste = fields.Char(u'Poste', size=254, readonly=True)
    matricule = fields.Char(u'Matricule', readonly=True)

    sexe = fields.Selection([('male', 'Male'), ('female', 'Female')], u'Genre', readonly=True)
    numero_cnaps = fields.Char(u'N° CNAPS', size=254, readonly=True)
    numero_cin = fields.Char(u'N° CIN', size=254, readonly=True)
    nom_lot_bulletin = fields.Char(u'Nom du lot de bulletin', size=254, readonly=True)
    debut_fiche_bulletin = fields.Date(u'Date début', readonly=True)
    fin_fiche_bulletin = fields.Date(u'Date fin', readonly=True)

    mode_paiement = fields.Char(u'Mode de paiement', size=254, readonly=True)
    etat_bulletin = fields.Selection(
        [('draft', 'Draft'),
         ('verify', 'Waiting'),
         ('waiting', 'Waiting'),
         ('done', 'Done'),
         ('cancel', 'Rejected'),
         ('canceled', 'Canceled')], u'Etat', readonly=True)
    lot_bulletin_id = fields.Char(u'Id du lot de bulletin', readonly=True)
    payslip_run_id = fields.Many2one('hr.payslip.run',string=u'Id du lot de bulletin', readonly=True)

    banque = fields.Char(u'Banque', size=254, readonly=True)
    code_banque = fields.Char(u'Code Banque', size=254, readonly=True)
    guichet = fields.Char(u'Code agence', size=254, readonly=True)
    numero_compte = fields.Char(u'N° de compte', size=254, readonly=True)

    company_id = fields.Many2one('res.company', string='Company', readonly=True)

    sb = fields.Float(u'Salaire de Base (SB)')
    tj = fields.Float(u'Taux journalier')
    th = fields.Float(u'Taux horaire')
    sb_j = fields.Float(u'Salaire selon jour travaillé')
    avtg_nat = fields.Float(u'Avantage en nature')
    idmt_alg_frs = fields.Float(u'Indemnité d\'allègement frais')
    idmt_logement = fields.Float(u'Indemnité de logement')
    idmt_depl = fields.Float(u'Indemnité de déplacement')
    idmt_diverses = fields.Float(u'Indemnité diverses')
    idmt_var_depl = fields.Float(u'Indemnité variable de déplacement')
    compl_repas = fields.Float(u'Complément repas')
    coms = fields.Float(u'Commission')
    prime_chnt = fields.Float(u'Prime de chantier')
    prime_chnt_air = fields.Float(u'Prime de chantier Aéroport')
    prime_prod = fields.Float(u'Prime de productivité')
    prime_fct = fields.Float(u'Prime de fonction')
    prime_expt = fields.Float(u'Prime exceptionnelle')
    prime_asdt = fields.Float(u'Prime d\'assiduité')
    prime_rdmnt = fields.Float(u'Prime de rendement')
    prime_cpmnt = fields.Float(u'Prime de comportement')
    primes_diverses = fields.Float(u'Primes diverses')
    prime_astr = fields.Float(u'Prime d\'astreinte')
    prime_grtf = fields.Float(u'Prime de gratification')
    prime_fin_annee = fields.Float(u'Prime de fin d\'année')
    prime_var_mens = fields.Float(u'Prime variable mensuelle')
    prime_obj_m1 = fields.Float(u'Prime Objectif M-1')
    prime_ca_m1 = fields.Float(u'Prime CA M-1')
    prime_hyg_srv_m1 = fields.Float(u'Prime hygiène / Service M-1')
    prime_clo_exr = fields.Float(u'Prime clôture exercice')
    prime_intrs = fields.Float(u'Prime intéressement')
    prime_anciennete = fields.Float(u'Prime d\' ancienneté')
    hs_130 = fields.Float(u'HS 130% (heure supplémentaire)')
    hs_150 = fields.Float(u'HS 150% (heure supplémentaire)')
    hn_30 = fields.Float(u'HN (heure de nuit) 30%')
    hn_50 = fields.Float(u'HN (heure de nuit) 50%')
    md_40 = fields.Float(u'Majoration Dimanche (40%)')
    mf_100 = fields.Float(u'Majoration férié (100%)')
    alloc_conge = fields.Float(u'Allocation de congé')
    icc = fields.Float(u'Indemnité compensatrice de congé')
    abs_conge = fields.Float(u'Absence congé')
    abs_rem_aut = fields.Float(u'Absence rémunérée autorisée')
    abs_non_rem = fields.Float(u'Absence non rémunérée')
    brut = fields.Float(u'Salaire brut')
    cnaps_pat = fields.Float(u'CNAPS Patronale')
    ostie_pat = fields.Float(u'OSTIE Patronale')
    fmfp = fields.Float(u'FMFP')
    cnaps = fields.Float(u'CNAPS')
    ostie = fields.Float(u'OSTIE')
    rappel_salaire = fields.Float(u'Rappel sur salaire')
    rappel_alloc_conge = fields.Float(u'Rappel sur les allocations de congé')
    rappel_prime_chantier = fields.Float(u'Rappel prime de chantier')
    rappel_prime_prod = fields.Float(u'Rappel prime de productivité')
    rappel_prime_fin_annee = fields.Float(u'Rappel prime de fin d\'année')
    rappel_prime_anciennete = fields.Float(u'Rappel prime d\'ancienneté')
    rappel_prime_clo_exr = fields.Float(u'Rappel prime clôture exercice')
    rappel_prime_astr = fields.Float(u'Rappel prime d\'astreinte')
    rappel_prime_hyg_srv_m1 = fields.Float(u'Rappel prime hygiène / Service M-1')
    rappel_prime_obj_m1 = fields.Float(u'Rappel prime objectif M-1')
    rappel_prime_chantier_air = fields.Float(u'Rappel prime de chantier aéroport')
    rappel_primes_diverses = fields.Float(u'Rappel primes diverses')
    rappel_prime_intrs = fields.Float(u'Rappel prime intéressement')
    rappel_prime_var_mens = fields.Float(u'Rappel prime variable mensuelle')
    rappel_prime_grtf = fields.Float(u'Rappel prime de gratification')
    rappel_prime_cpmnt = fields.Float(u'Rappel prime de comportement')
    rappel_prime_asdt = fields.Float(u'Rappel prime d\'assiduité')
    rappel_prime_ca_m1 = fields.Float(u'Rappel prime CA M-1')
    rappel_prime_rdmnt = fields.Float(u'Rappel prime de rendement')
    rappel_prime_fct = fields.Float(u'Rappel prime de fonction')
    rappel_prime_expt = fields.Float(u'Rappel prime exceptionnelle')
    mi = fields.Float(u'Montant Imposable (MI)')
    irsa = fields.Float(u'IRSA')
    avc_quinzaine = fields.Float(u'Avance quinzaine')
    avc_spec = fields.Float(u'Avance spéciale')
    alloc_fam = fields.Float(u'Allocation familiale')
    sal_net = fields.Float(u'Salaire Net')

    avance_scolaire = fields.Float(u'Avance scolaire')
    prime_rappel_risque = fields.Float(u'Prime rappel de risque')
    indemnite_preavis = fields.Float(u'Indemnité de préavis')
    demi_salaire_maternite = fields.Float(u'Demi salaire maternité')
    absence_pour_conge_maternite = fields.Float(u'Absence pour congé de maternité')
    prime_de_risque = fields.Float(u'Prime de risque')
    indmt_stage = fields.Float(u'Indemnité de stage')
    
    commission_sur_vente = fields.Float(u'Commission sur vente')
    ded_enfant_a_charge = fields.Float(u'Déduction enfant à charge')
    indemnite_de_licenciement = fields.Float(u'Indemnité de licenciement')
    indemnite_de_logement_non_imposable = fields.Float(u'Indemnité de logement non imposable')
    irsa_brut = fields.Float(u'IRSA BRUT')
    mise_a_pied = fields.Float(u'Mise à pied')
    preavis_non_effectue = fields.Float(u'Préavis non effectué')
    prime_de_depart = fields.Float(u'Prime de départ')
    prime_de_retraite = fields.Float(u'Prime de retraite')
    prime_interessement = fields.Float(u'Prime intéressement')
    prime_d_interessement = fields.Float(u'Prime d\'intéressement')
    rappel = fields.Float(u'Rappel')
    regul_cnaps = fields.Float(u'Régul CNAPS')
    regul_ostie = fields.Float(u'Régul OSTIE')
    retraite_complementaire = fields.Float(u'Retraite complémentaire')

